### ISSUE TITLE
No such export methRunReport in resource ps-dispatch

### ISSUE THREAD

**Issue by primoixi** [Lanzaned-Enterprises/LENT-Drugrun#1]
Sir can you provide help regarding No such export methRunReport in resource ps-dispatch script facing issues during deliver goods.

**Comment by SerenaKing** [comment]
My apologies for the late reply to this like insanely late. But this was never a logged resource haha. You can find a way better version over here: [Drug Run LANZANED](https://github.com/Lanzaned-Enterprises/LENT-CliffordRun/tree/main)
